baseurl = "http://www.wooditforyou.be"
title = "WoodItForYou"
theme = "dimension"
languageCode = "en-us"
defaultContentLanguage = "fr"
enableRobotsTXT = true
disableKinds=["RSS"]
publishDir = "htdocs"

[params]
  description = '<!--[-->Designer d émotions & Fusionneur de matières<!--]--><br />'
  logo = "fa-diamond"
  copyright = "Untitled"

[[params.social]]
  medium = "pinterest"
  icon = "pinterest"
  link = "https://www.pinterest.com/Wooditforyou/"

[[params.social]]
  medium = "facebook"
  icon = "facebook"
  link = "https://www.facebook.com/wooditforyou.be"

[[params.social]]
  medium = "instagram"
  icon = "instagram"
  link = "https://www.instagram.com/wooditforyou/"

[[params.social]]
  medium = "youtube"
  icon = "youtube"
  link = "https://www.youtube.com/channel/UC91atDm-rg0cEYstxsMRKkg"

[languages]
[languages.fr]
languageName = "Francais"
weight = 1

[languages.nl]
languageName = "Nederlands"
weight = 2
title = "Wooditforyou"
description = '<!--[-->A fully responsive site template designed by <a href="https://html5up.net">HTML5 UP</a> and released<!--]--><br />
                <!--[-->for free under the <a href="https://html5up.net/license">Creative Commons</a> license.<!--]-->'
